# -*- coding: utf-8 -*-
"""integration part

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11VqWWXc-ogFPNHjCP07ariOEp6ylXipo

Input Request Payload (Backend -> ML Engine)
"""

{
  "candidate_form": {
    "Name": "Aryan Kumar",
    "Skills": "Python, PyTorch, SQL, FastAPI",
    "Experience (Years)": 1,
    "Education": "B.Tech",
    "Certifications": "AWS Certified Solutions Architect",
    "Job Role": "Machine Learning Engineer",
    "Projects Count": 4,
    "Salary Expectation ($)": 50000,
    "GitHub_URL": "https://github.com/torvalds",
    "LinkedIn_URL": "https://linkedin.com/in/linustorvalds"
  },
  "resume_file_path": "uploads/resumes/aryan_resume.pdf",
  "has_certification_proof": true,
  "coding_assessment_score": 8
}

"""**Response Payload (ML Engine -> Backend)**"""

{
  "candidate_name": "Aryan Kumar",
  "target_role": "Machine Learning Engineer",
  "raw_ml_match_score": 88.5,
  "penalties": {
    "white_text_fraud_penalty": 0.0,
    "missing_cert_proof_penalty": 0.0,
    "total_penalties": 0.0
  },
  "bonuses": {
    "github_proof_of_work_bonus": 8.5,
    "linkedin_presence_bonus": 5.0,
    "coding_assessment_bonus": 8.0,
    "total_bonuses": 21.5
  },
  "final_ai_match_score": 100.0,
  "final_decision_status": "Shortlisted",
  "fraud_detected": false,
  "github_analytics": {
    "valid": true,
    "public_repos": 12,
    "tech_stack": ["Python", "C++", "C"]
  },
  "role_specific_recommendations": [
    "Learn 'Docker' to fulfill core requirements for 'Machine Learning Engineer'.",
    "Learn 'MLOps' to fulfill core requirements for 'Machine Learning Engineer'."
  ]
}

"""**Standardized Backend ML Module (ml_engine.py)**"""

# =====================================================================
# PS 26044: STANDARDIZED PRODUCTION ML ENGINE MODULE (ml_engine.py)
# Compatible with: Antigravity, VS Code, FastAPI, Django, Flask
# =====================================================================

import os
import re
import joblib
import requests
import pdfplumber
import pytesseract
import cv2
import pandas as pd
import numpy as np
from pdf2image import convert_from_path

# ---------------------------------------------------------------------
# 1. LOAD TRAINED MODEL ARTIFACTS
# ---------------------------------------------------------------------
MODEL_DIR = os.path.dirname(os.path.abspath(__file__))
CLF_MODEL_PATH = os.path.join(MODEL_DIR, 'screening_classifier_gb.pkl')
REG_MODEL_PATH = os.path.join(MODEL_DIR, 'screening_regressor_gb.pkl')

try:
    clf_model = joblib.load(CLF_MODEL_PATH)
    reg_model = joblib.load(REG_MODEL_PATH)
    print("✅ ML Engine: Trained models (.pkl) loaded successfully.")
except Exception as e:
    print(f"⚠️ ML Engine Warning: Could not load .pkl files. Check path: {e}")


# ---------------------------------------------------------------------
# 2. RESUME PARSING & WHITE-TEXT FRAUD INSPECTION
# ---------------------------------------------------------------------
def inspect_and_extract_resume(file_path: str) -> dict:
    if not file_path or not os.path.exists(file_path):
        return {"extracted_text": "", "fraud_detected": False, "hidden_keywords": [], "penalty": 0.0}

    hidden_keywords = []
    is_scanned_pdf = False
    extracted_text = ""

    # Digital PDF Processing
    if file_path.lower().endswith('.pdf'):
        try:
            with pdfplumber.open(file_path) as pdf:
                for page in pdf.pages:
                    words = page.extract_words(extra_attrs=["non_stroking_color", "size"])
                    if not words:
                        is_scanned_pdf = True

                    for word in words:
                        text = word['text']
                        font_size = word['size']
                        color = word.get('non_stroking_color')

                        is_white = color in [(1, 1, 1), (255, 255, 255), [1, 1, 1], [255, 255, 255]]
                        is_tiny = font_size < 3.0

                        if is_white or is_tiny:
                            hidden_keywords.append(text)

                    extracted_text += (page.extract_text() or "") + "\n"
        except Exception:
            is_scanned_pdf = True

    # OCR Fallback for Scanned PDF or Image
    if is_scanned_pdf or file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
        try:
            if file_path.lower().endswith(('.png', '.jpg', '.jpeg')):
                img = cv2.imread(file_path)
                extracted_text = pytesseract.image_to_string(img)
            else:
                images = convert_from_path(file_path)
                for img in images:
                    extracted_text += pytesseract.image_to_string(img) + "\n"
        except Exception as e:
            print(f"OCR Error: {e}")

    is_fraudulent = len(hidden_keywords) > 0
    penalty = -20.0 if is_fraudulent else 0.0

    return {
        "extracted_text": extracted_text.strip(),
        "fraud_detected": is_fraudulent,
        "hidden_keywords": hidden_keywords,
        "penalty": penalty
    }


# ---------------------------------------------------------------------
# 3. ENTITY EXTRACTION & EXTERNAL API PROOFS
# ---------------------------------------------------------------------
def extract_social_links(text: str) -> dict:
    github_pattern = r'https?://(?:www\.)?github\.com/[a-zA-Z0-9_-]+'
    linkedin_pattern = r'https?://(?:www\.)?linkedin\.com/in/[a-zA-Z0-9_-]+'

    gh = re.findall(github_pattern, text, re.IGNORECASE)
    li = re.findall(linkedin_pattern, text, re.IGNORECASE)

    return {
        "github_url": gh[0] if gh else None,
        "linkedin_url": li[0] if li else None
    }

def analyze_github(github_url: str) -> dict:
    if not github_url:
        return {"valid": False, "score": 0.0, "public_repos": 0, "tech_stack": []}

    username = github_url.strip().rstrip('/').split('github.com/')[-1].split('/')[0]
    headers = {"User-Agent": "Mozilla/5.0"}

    try:
        u_res = requests.get(f"https://api.github.com/users/{username}", headers=headers, timeout=4)
        if u_res.status_code != 200:
            return {"valid": False, "score": 0.0, "public_repos": 0, "tech_stack": []}

        u_data = u_res.json()
        public_repos = u_data.get('public_repos', 0)

        r_res = requests.get(f"https://api.github.com/users/{username}/repos?per_page=100", headers=headers, timeout=4)
        stars = 0
        langs = set()
        if r_res.status_code == 200:
            for repo in r_res.json():
                if not repo.get('fork', False):
                    stars += repo.get('stargazers_count', 0)
                    if repo.get('language'):
                        langs.add(repo.get('language'))

        score = min(100.0, (min(30, public_repos * 3) + min(30, stars * 5) + min(20, len(langs) * 5) + (20 if public_repos > 0 else 0)))
        return {"valid": True, "score": score, "public_repos": public_repos, "tech_stack": list(langs)}
    except Exception:
        return {"valid": False, "score": 0.0, "public_repos": 0, "tech_stack": []}


# ---------------------------------------------------------------------
# 4. RECOMMENDATIONS ENGINE
# ---------------------------------------------------------------------
def get_role_recommendations(candidate_skills: list, role: str) -> list:
    benchmarks = {
        'machine learning intern': ['Python', 'Scikit-Learn', 'Pandas', 'NumPy', 'SQL', 'Git'],
        'machine learning engineer': ['Python', 'PyTorch', 'TensorFlow', 'FastAPI', 'Docker', 'MLOps', 'SQL'],
        'ai researcher': ['Python', 'PyTorch', 'TensorFlow', 'Deep Learning', 'NLP', 'Computer Vision'],
        'data scientist': ['Python', 'SQL', 'Pandas', 'Statistics', 'Scikit-Learn', 'Tableau']
    }
    required = benchmarks.get(role.lower().strip(), ['Python', 'SQL', 'Git', 'Docker'])
    cand_lower = [s.lower().strip() for s in candidate_skills]
    missing = [s for s in required if s.lower() not in cand_lower]

    return [f"Learn '{m}' to fulfill core requirements for '{role}'." for m in missing]


# ---------------------------------------------------------------------
# 5. MAIN EVALUATION FUNCTION (BACKEND ENTRY POINT)
# ---------------------------------------------------------------------
def evaluate_candidate(candidate_payload: dict) -> dict:
    """
    Main function to be called by Backend Developer (FastAPI / Express Controller)
    """
    form = candidate_payload.get("candidate_form", {})
    file_path = candidate_payload.get("resume_file_path")
    has_cert_proof = candidate_payload.get("has_certification_proof", True)
    coding_score = candidate_payload.get("coding_assessment_score", 0) # 0 to 10

    # 1. Resume Inspection
    resume_analysis = inspect_and_extract_resume(file_path)

    # 2. ML Baseline Model Prediction
    df_input = pd.DataFrame([form])
    raw_ml_score = float(reg_model.predict(df_input)[0])
    ml_decision = int(clf_model.predict(df_input)[0])

    # 3. Social Auto Link Extraction
    links = extract_social_links(resume_analysis["extracted_text"])
    gh_url = form.get("GitHub_URL") or links["github_url"]
    li_url = form.get("LinkedIn_URL") or links["linkedin_url"]

    gh_data = analyze_github(gh_url)
    has_linkedin = bool(li_url and "linkedin.com/in/" in li_url.lower())

    # 4. Score Math
    white_text_penalty = resume_analysis["penalty"] # -20.0 if fraud
    cert_penalty = 0.0 if (has_cert_proof or form.get("Certifications", "None").lower() == "none") else -5.0

    github_bonus = (gh_data["score"] / 100.0) * 10.0
    linkedin_bonus = 5.0 if has_linkedin else 0.0
    coding_bonus = float(coding_score) * 1.0 # 1 Mark = +1%

    total_penalty = white_text_penalty + cert_penalty
    total_bonus = github_bonus + linkedin_bonus + coding_bonus

    final_score = max(0.0, min(100.0, raw_ml_score + total_penalty + total_bonus))

    # Decision
    if resume_analysis["fraud_detected"]:
        status = "Rejected / Flagged (Hidden White-Text Fraud Detected)"
    elif cert_penalty < 0:
        status = "Shortlisted with Warning (Missing Certification Proof)"
    elif ml_decision == 1:
        status = "Shortlisted"
    else:
        status = "Rejected (Low Skill Match)"

    skills_list = [s.strip() for s in form.get("Skills", "").split(",")]
    recs = get_role_recommendations(skills_list, form.get("Job Role", ""))

    return {
        "candidate_name": form.get("Name", "Applicant"),
        "target_role": form.get("Job Role", "N/A"),
        "raw_ml_match_score": round(raw_ml_score, 2),
        "penalties": {
            "white_text_fraud_penalty": white_text_penalty,
            "missing_cert_proof_penalty": cert_penalty,
            "total_penalties": total_penalty
        },
        "bonuses": {
            "github_proof_of_work_bonus": round(github_bonus, 2),
            "linkedin_presence_bonus": linkedin_bonus,
            "coding_assessment_bonus": coding_bonus,
            "total_bonuses": round(total_bonus, 2)
        },
        "final_ai_match_score": round(final_score, 2),
        "final_decision_status": status,
        "fraud_detected": resume_analysis["fraud_detected"],
        "github_analytics": gh_data,
        "role_specific_recommendations": recs
    }

"""**i think this is for flask may be not sure**"""

from ml_engine import evaluate_candidate

@app.post("/api/evaluate-candidate")
def process_evaluation(payload: dict):
    # Payload frontend se aayega
    result = evaluate_candidate(payload)
    return result